ARCHIVE_EXTENSION = 'azar'

ENCODING = 'utf-8'
BYTE_ORDER = 'little'

MAGIC_HEADER = 'azAR'.encode(ENCODING)
MAGIC_SEPARATOR = 'RAza'.encode(ENCODING)
SYMBOL_SEPARATOR = '🎃'.encode(ENCODING)

INT_LENGTH = 4
SYMBOL_LENGTH = 2

ENGLISH_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
RUSSIAN_ALPHABET = 'АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'
